function New-LWASLauncherScript {
    <#
    .SYNOPSIS
        Generates a launcher .ps1 script file for a Windows Scheduled Task.

    .DESCRIPTION
        Creates a dedicated launcher script at
        $env:APPDATA\LastWarAutoScreenshot\Schedulers\<TaskName>.ps1.
        The script imports the LWAS module then pipes Get-LWASTargetWindow into
        Start-LWASAutomationSequence. The Schedulers directory is created automatically
        if it does not already exist.

        Returns the full path of the created launcher file.

    .PARAMETER TaskName
        The scheduled task name (e.g. 'LWAS_my-macro'). Used as the launcher filename.

    .PARAMETER MacroName
        The macro to execute. Embedded in the launcher script body.

    .PARAMETER ProcessName
        The target process name (e.g. 'lastwar.exe'). Embedded in the launcher script body.

    .PARAMETER ModulePath
        Absolute path to the module manifest (.psd1). Embedded as the Import-Module path.

    .OUTPUTS
        string
        The full path to the generated launcher script file.

    .EXAMPLE
        $path = New-LWASLauncherScript -TaskName 'LWAS_my-macro' -MacroName 'my-macro' `
            -ProcessName 'lastwar.exe' -ModulePath 'C:\Modules\LastWarAutoScreenshot.psd1'

    .NOTES
        The generated launcher file must be deleted by Unregister-LWASScheduledTask when
        the corresponding scheduled task is removed, to prevent orphaned scripts.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [string]$TaskName,

        [Parameter(Mandatory)]
        [string]$MacroName,

        [Parameter(Mandatory)]
        [string]$ProcessName,

        [Parameter(Mandatory)]
        [string]$ModulePath
    )

    $launcherPath = Join-Path $env:APPDATA "LastWarAutoScreenshot\Schedulers\$TaskName.ps1"
    $schedulersDir = Split-Path -Parent $launcherPath

    New-Item -ItemType Directory -Path $schedulersDir -Force | Out-Null

    $generatedAt = [datetime]::UtcNow.ToString('o')

    $content = @"
# LWAS Launcher — auto-generated by Register-LWASScheduledTask — do not edit manually
# Task    : $TaskName
# Macro   : $MacroName
# Generated: $generatedAt
`$ErrorActionPreference = 'Stop'
Import-Module '$ModulePath' -ErrorAction Stop
Get-LWASTargetWindow -ProcessName '$ProcessName' |
    Start-LWASAutomationSequence -MacroName '$MacroName'
"@

    Set-Content -Path $launcherPath -Value $content -Encoding UTF8

    return $launcherPath
}
