BeforeAll {
    $moduleManifest = Join-Path (Split-Path -Parent $PSScriptRoot) 'LastWarAutoScreenshot.psd1'
    Import-Module $moduleManifest -Force
}

Describe 'New-LWASLauncherScript' -Tag 'Unit' {

    BeforeEach {
        InModuleScope LastWarAutoScreenshot -Parameters @{ td = $TestDrive } {
            # Override APPDATA so all file I/O goes to TestDrive
            $env:APPDATA = $td
        }
    }

    AfterEach {
        InModuleScope LastWarAutoScreenshot {
            $env:APPDATA = [System.Environment]::GetFolderPath('ApplicationData')
        }
    }

    It 'Creates the launcher file at the expected path' {
        InModuleScope LastWarAutoScreenshot -Parameters @{ td = $TestDrive } {
            $result = New-LWASLauncherScript `
                -TaskName 'LWAS_my-macro' `
                -MacroName 'my-macro' `
                -ProcessName 'lastwar.exe' `
                -ModulePath 'C:\Modules\LastWarAutoScreenshot.psd1'

            $expectedPath = Join-Path $td 'LastWarAutoScreenshot\Schedulers\LWAS_my-macro.ps1'
            Test-Path -LiteralPath $expectedPath | Should -BeTrue
        }
    }

    It 'Returns the expected launcher file path string' {
        InModuleScope LastWarAutoScreenshot -Parameters @{ td = $TestDrive } {
            $result = New-LWASLauncherScript `
                -TaskName 'LWAS_my-macro' `
                -MacroName 'my-macro' `
                -ProcessName 'lastwar.exe' `
                -ModulePath 'C:\Modules\LastWarAutoScreenshot.psd1'

            $expectedPath = Join-Path $td 'LastWarAutoScreenshot\Schedulers\LWAS_my-macro.ps1'
            $result | Should -BeExactly $expectedPath
        }
    }

    It 'File content contains Import-Module with the supplied module path' {
        InModuleScope LastWarAutoScreenshot -Parameters @{ td = $TestDrive } {
            New-LWASLauncherScript `
                -TaskName 'LWAS_my-macro' `
                -MacroName 'my-macro' `
                -ProcessName 'lastwar.exe' `
                -ModulePath 'C:\Modules\LastWarAutoScreenshot.psd1' | Out-Null

            $content = Get-Content -Path (Join-Path $td 'LastWarAutoScreenshot\Schedulers\LWAS_my-macro.ps1') -Raw
            $content | Should -BeLike "*Import-Module 'C:\Modules\LastWarAutoScreenshot.psd1'*"
        }
    }

    It 'File content contains Get-LWASTargetWindow with the supplied process name' {
        InModuleScope LastWarAutoScreenshot -Parameters @{ td = $TestDrive } {
            New-LWASLauncherScript `
                -TaskName 'LWAS_my-macro' `
                -MacroName 'my-macro' `
                -ProcessName 'lastwar.exe' `
                -ModulePath 'C:\Modules\LastWarAutoScreenshot.psd1' | Out-Null

            $content = Get-Content -Path (Join-Path $td 'LastWarAutoScreenshot\Schedulers\LWAS_my-macro.ps1') -Raw
            $content | Should -BeLike "*Get-LWASTargetWindow -ProcessName 'lastwar.exe'*"
        }
    }

    It 'File content contains Start-LWASAutomationSequence with the supplied macro name' {
        InModuleScope LastWarAutoScreenshot -Parameters @{ td = $TestDrive } {
            New-LWASLauncherScript `
                -TaskName 'LWAS_my-macro' `
                -MacroName 'my-macro' `
                -ProcessName 'lastwar.exe' `
                -ModulePath 'C:\Modules\LastWarAutoScreenshot.psd1' | Out-Null

            $content = Get-Content -Path (Join-Path $td 'LastWarAutoScreenshot\Schedulers\LWAS_my-macro.ps1') -Raw
            $content | Should -BeLike "*Start-LWASAutomationSequence -MacroName 'my-macro'*"
        }
    }

    It 'File content contains the auto-generated header with task name and macro name' {
        InModuleScope LastWarAutoScreenshot -Parameters @{ td = $TestDrive } {
            New-LWASLauncherScript `
                -TaskName 'LWAS_my-macro' `
                -MacroName 'my-macro' `
                -ProcessName 'lastwar.exe' `
                -ModulePath 'C:\Modules\LastWarAutoScreenshot.psd1' | Out-Null

            $content = Get-Content -Path (Join-Path $td 'LastWarAutoScreenshot\Schedulers\LWAS_my-macro.ps1') -Raw
            $content | Should -BeLike '*auto-generated by Register-LWASScheduledTask*'
            $content | Should -BeLike '*Task    : LWAS_my-macro*'
            $content | Should -BeLike '*Macro   : my-macro*'
        }
    }

    It 'Creates the Schedulers directory when it does not already exist' {
        InModuleScope LastWarAutoScreenshot -Parameters @{ td = $TestDrive } {
            $schedulersDir = Join-Path $td 'LastWarAutoScreenshot\Schedulers'
            # Remove the directory in case a previous test created it
            Remove-Item -Path $schedulersDir -Recurse -Force -ErrorAction SilentlyContinue
            Test-Path -LiteralPath $schedulersDir | Should -BeFalse

            New-LWASLauncherScript `
                -TaskName 'LWAS_dir-test' `
                -MacroName 'dir-test' `
                -ProcessName 'game.exe' `
                -ModulePath 'C:\Modules\LastWarAutoScreenshot.psd1' | Out-Null

            Test-Path -LiteralPath $schedulersDir | Should -BeTrue
        }
    }
}
